version: '3'

services:
  db_test:
    image: mariadb:10.2
    container_name: db-test
    restart: always
    ports:
      - 5306:3306
    expose:
      - 3306
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_allowed_packet=256M
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - backend
    env_file:
      - ./api/shared/.env
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      interval: 5s
      timeout: 3s
      retries: 10

  api_auth:
    build:
      context: api/
      dockerfile: auth/Dockerfile
    command: 'run start:test'
    container_name: api-auth-test
    restart: always
    ports:
      - 5201:5201
    expose:
      - 5201
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
    environment:
      PORT: 5201
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5201']
      interval: 5s
      timeout: 3s
      retries: 10

  api_global:
    build:
      context: api/
      dockerfile: global/Dockerfile
    command: 'run start:test'
    container_name: api-global-test
    restart: always
    ports:
      - 5202:5202
    expose:
      - 5202
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
    environment:
      PORT: 5202
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5202']
      interval: 5s
      timeout: 3s
      retries: 10

  api_groceries:
    build:
      context: api/
      dockerfile: groceries/Dockerfile
    command: 'run start:test'
    container_name: api-groceries-test
    restart: always
    ports:
      - 5203:5203
    expose:
      - 5203
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
      - api_global
      - api_homes
    environment:
      PORT: 5203
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5203']
      interval: 5s
      timeout: 3s
      retries: 10

  api_homes:
    build:
      context: api/
      dockerfile: homes/Dockerfile
    command: 'run start:test'
    container_name: api-homes-test
    restart: always
    ports:
      - 5204:5204
    expose:
      - 5204
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
      - api_global
    environment:
      PORT: 5204
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5204']
      interval: 5s
      timeout: 3s
      retries: 10

  api_tasks:
    build:
      context: api/
      dockerfile: tasks/Dockerfile
    command: 'run start:test'
    container_name: api-tasks-test
    restart: always
    ports:
      - 5205:5205
    expose:
      - 5205
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
      - api_global
      - api_homes
    environment:
      PORT: 5205
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5205']
      interval: 5s
      timeout: 3s
      retries: 10

  api_accounts:
    build:
      context: api/
      dockerfile: accounts/Dockerfile
    command: 'run start:test'
    container_name: api-accounts-test
    restart: always
    ports:
      - 5206:5206
    expose:
      - 5206
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
      - api_global
      - api_homes
    environment:
      PORT: 5206
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5206']
      interval: 5s
      timeout: 3s
      retries: 10

  api_calendar:
    build:
      context: api/
      dockerfile: calendar/Dockerfile
    command: 'run start:test'
    container_name: api-calendar-test
    restart: always
    ports:
      - 5207:5207
    expose:
      - 5207
    networks:
      - backend
    links:
      - db_test
    depends_on:
      - db_test
      - api_auth
      - api_global
      - api_homes
    environment:
      PORT: 5207
      DB_HOST: db_test
      DB_PORT: 3306
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:5207']
      interval: 5s
      timeout: 3s
      retries: 10

  api_test:
    build:
      context: api/
      dockerfile: test/Dockerfile
    container_name: api-test
    ports:
      - 5219:5219
    expose:
      - 5219
    networks:
      - backend
    links:
      - db_test
    depends_on:
      db_test:
        condition: service_healthy
      api_auth:
        condition: service_healthy
      api_global:
        condition: service_healthy
      api_homes:
        condition: service_healthy
      api_tasks:
        condition: service_healthy
      api_groceries:
        condition: service_healthy
      api_calendar:
        condition: service_healthy
      api_accounts:
        condition: service_healthy
    environment:
      PORT: 5219
      DB_HOST: db_test
      DB_PORT: 3306
      IP_AUTH: api_auth
      PORT_AUTH: 5201
      IP_GLOBAL: api_global
      PORT_GLOBAL: 5202
      IP_GROCERIES: api_groceries
      PORT_GROCERIES: 5203
      IP_HOMES: api_homes
      PORT_HOMES: 5204
      IP_TASKS: api_tasks
      PORT_TASKS: 5205
      IP_ACCOUNTS: api_accounts
      PORT_ACCOUNTS: 5206
      IP_CALENDAR: api_calendar
      PORT_CALENDAR: 5207

volumes:
  db_test:
    driver: local

networks:
  backend:
    driver: bridge
