name: Node.js CI

on:
  push:
    branches: [main, dev-antoine]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v${{ matrix.node-version }}
        # working-directory: ./api
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
      - name: Start MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql database: 'cotulity_test'
          mysql root password: ${{ secrets.DB_ROOT_PWD }}
          mysql user: 'cot_test'
          mysql password: ${{ secrets.DB_TEST_PWD }}
      - name: Install packages
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
