name: Node.js CI

on:
  pull_request:
  push:
    branches: [main, dev-antoine]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      DB_TEST: ${{ secrets.DB_TEST }}
      DB_TEST_PWD: ${{ secrets.DB_TEST_PWD }}
      DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      PORT_AUTH: '2999'
      PORT_GLOBAL: '3000'
      PORT_GROCERIES: '3001'
      PORT_HOMES: '3002'
      PORT_TASKS: '3003'
      PORT_ACCOUNTS: '3004'
      PORT_CALENDAR: '3005'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build microservices and test containers
        run: docker-compose -f docker-compose-test-git.yml build

      - name: Start test microservice
        run: docker-compose -f docker-compose-test-git.yml up db_test

      - name: Start auth microservice
        run: docker-compose -f docker-compose-test-git.yml up api_auth

      - name: Start global microservice
        run: docker-compose -f docker-compose-test-git.yml up api_global

      - name: Start groceries microservice
        run: docker-compose -f docker-compose-test-git.yml up api_groceries

      - name: Start homes microservice
        run: docker-compose -f docker-compose-test-git.yml up api_homes

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Run Tests
        run: docker-compose -f docker-compose-test-git.yml up api_test --abort-on-container-exit
