name: Node.js CI

on:
  push:
    branches: [main, dev-antoine]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v${{ matrix.node-version }}
        # working-directory: ./api
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # - name: Build Docker images
      #   run: docker-compose build
      - name: Install packages
        working-directory: ./api
        run: npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
